# Generated by Django 4.2 on 2023-05-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='Ruc')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('contacto', models.CharField(max_length=50, verbose_name='Contacto')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo Electronico')),
                ('nombreContador', models.CharField(max_length=50, verbose_name='Nombre Contador')),
                ('rucContador', models.CharField(max_length=50, verbose_name='Ruc del Contador')),
                ('nombreRlegal', models.CharField(max_length=50, verbose_name='Nombre Representante Legal')),
                ('rucRlegal', models.CharField(max_length=50, verbose_name='Ruc del Representante Legal')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Unegocio',
                'ordering': ['nombre'],
            },
        ),
    ]
